name: Publish Release

on:
  push:
    branches:
      - send-mail-action
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  Build_AAP:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Clean project
        run: ./gradlew clean

      - name: Build Release AAP
        run: ./gradlew :app:bundleRelease

      - name: Sign AAP
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGN_KEY }}
          alias: ${{ secrets.SIGN_ALIAS }}
          keyStorePassword: ${{ secrets.SIGN_KEY_PASSWORD }}
          keyPassword: ${{ secrets.SIGN_KEY_PASSWORD }}

      - name: Upload AAP
        uses: actions/upload-artifact@v2
        with:
          name: aap-release
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}

      - name: Check files
        run: ls
